[project]
name = "eer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awkward>=2.9.0",
    "einops>=0.8.2",
    "loguru>=0.7.3",
    "mne>=1.11.0",
    "pandas>=3.0.0",
    "pymupdf>=1.27.2.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "torch~=2.6.0",
    "torch-geometric>=2.7.0",
    "typer>=0.21.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

